#include "SettingsViewController.hpp"
#include "VideoPlayerConfig.hpp"
#include "VideoPlayerController.hpp"
#include "main.hpp"
#include "assets.hpp"    // generated by CMake via cmrc / inline resources

#include "bsml/shared/BSML-Lite.hpp"
#include "bsml/shared/BSML/MainThreadScheduler.hpp"

DEFINE_TYPE(VideoPlayer, SettingsViewController);

// ── BSML Properties ──────────────────────────────────────────────────────────

#define CFG_PROP(Type, Name, CfgKey)                                \
    Type VideoPlayer::SettingsViewController::get_##Name()          \
        { return getVideoPlayerConfig().CfgKey.GetValue(); }        \
    void VideoPlayer::SettingsViewController::set_##Name(Type v)    \
        { getVideoPlayerConfig().CfgKey.SetValue(v); }

CFG_PROP(float,   posX,      PosX)
CFG_PROP(float,   posY,      PosY)
CFG_PROP(float,   posZ,      PosZ)
CFG_PROP(float,   rotX,      RotX)
CFG_PROP(float,   rotY,      RotY)
CFG_PROP(float,   rotZ,      RotZ)
CFG_PROP(float,   scaleX,    ScaleX)
CFG_PROP(float,   scaleY,    ScaleY)
CFG_PROP(float,   volume,    Volume)
CFG_PROP(bool,    loop,      Loop)
CFG_PROP(bool,    autoPlay,  AutoPlay)
CFG_PROP(float,   curvature, Curvature)

StringW VideoPlayer::SettingsViewController::get_videoPath()
    { return getVideoPlayerConfig().VideoPath.GetValue(); }
void VideoPlayer::SettingsViewController::set_videoPath(StringW v)
    { getVideoPlayerConfig().VideoPath.SetValue(static_cast<std::string>(v)); }

// ── Activate ──────────────────────────────────────────────────────────────────

void VideoPlayer::SettingsViewController::DidActivate(
        bool firstActivation, bool, bool) {
    if (!firstActivation) return;
    BSML::parse_and_construct(
        Assets::settings_bsml,  // embedded BSML from assets.hpp
        get_transform(), this);
}

// ── Button handlers ───────────────────────────────────────────────────────────

void VideoPlayer::SettingsViewController::OnPlayClicked() {
    auto* ctrl = VideoPlayerController::GetInstance();
    if (ctrl) ctrl->Play();
}

void VideoPlayer::SettingsViewController::OnPauseClicked() {
    auto* ctrl = VideoPlayerController::GetInstance();
    if (ctrl) ctrl->Pause();
}

void VideoPlayer::SettingsViewController::OnStopClicked() {
    auto* ctrl = VideoPlayerController::GetInstance();
    if (ctrl) ctrl->Stop();
}

void VideoPlayer::SettingsViewController::OnReloadClicked() {
    auto* ctrl = VideoPlayerController::GetInstance();
    if (ctrl) ctrl->LoadVideo(getVideoPlayerConfig().VideoPath.GetValue());
}

void VideoPlayer::SettingsViewController::OnApplyClicked() {
    // Values already persisted via BSML property setters; apply to live screen
    getVideoPlayerConfig().Save();
    auto* ctrl = VideoPlayerController::GetInstance();
    if (ctrl) ctrl->ApplyConfig();
}
