#pragma once
// Auto-generated by CMake (cmrc / incbin pattern).
// The BSML XML is embedded as a null-terminated string literal so no
// file I/O is needed at runtime.

namespace Assets {

inline constexpr char settings_bsml[] =
#include "settings_bsml.inc"
;

} // namespace Assets
